# Generated by Django 3.1.7 on 2021-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPressApp', '0002_auto_20210313_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypress_pages',
            name='body',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
