# Generated by Django 3.1.7 on 2021-03-15 16:42

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyPressApp', '0006_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pypress_pages',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pypress_pages',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='pypress_pages',
            name='head',
        ),
        migrations.AddField(
            model_name='pypress_pages',
            name='post',
            field=django_ckeditor_5.fields.CKEditor5Field(default='a', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
